# Generated by Django 4.2.15 on 2025-03-28 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_allow_member_to_create_label_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perspective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "data_type",
                    models.CharField(
                        choices=[("int", "Integer"), ("string", "String"), ("boolean", "Boolean")], max_length=20
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="perspectives", to="projects.project"
                    ),
                ),
            ],
        ),
    ]
