# Generated by Django 4.2.15 on 2025-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_perspective"),
    ]

    operations = [
        migrations.AddField(
            model_name="perspective",
            name="options",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
