# Generated by Django 4.2.15 on 2025-04-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_perspective_perspectivegroup_perspectiveanswer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscrepanciesQuestions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("question", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="open", max_length=20)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="discrepancies", to="projects.project"
                    ),
                ),
            ],
        ),
    ]
