# Generated by Django 4.2.15 on 2025-06-12 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0008_assignment"),
        ("projects", "0009_perspective_perspectivegroup_perspectiveanswer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perspectiveanswer",
            name="example",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perspective_answers",
                to="examples.example",
            ),
        ),
    ]
