# Generated by Django 4.2.15 on 2025-04-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_tosubmitquestions"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("questions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("vote_end_date", models.DateTimeField(blank=True, null=True)),
                ("finish", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_sessions",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
