# Generated by Django 4.2.15 on 2025-06-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_perspectiveanswer_example"),
        ("projects", "0013_rulediscussionmessage"),
    ]

    operations = []
