# Generated by Django 4.2.15 on 2025-06-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_merge_20250614_1837"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=10),
        ),
    ]
