# Generated by Django 4.2.15 on 2025-06-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0016_segmentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="boundingbox",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="category",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="relation",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="segmentation",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="span",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="textlabel",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
