# Generated by Django 4.2.15 on 2025-06-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("label_types", "0007_delete_relationtypeold"),
        ("examples", "0008_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="label_types.categorytype",
            ),
        ),
    ]
