# Generated by Django 4.2.15 on 2025-06-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0008_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="label",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
